### ISSUE TITLE
Replace statistical phrases by calls to `likelihoodMap`

### ISSUE THREAD

**Issue by alfy91** [explorable-viz/authoring-assistant#10]
### Context

Using Large Language Models for the Generation of Strings that contains some fluid elements, useful for the creation of LinkedText in fluid

## Tasks

- [x] Use of LLM and prompting engineering for replacing statistical phrases (like virtually certain, unlikely etc) with the mapping function `likelihoodMap`
- [x] Use of LLM and prompting engineering for replacing numerical data available in tables with the related variables (e.g. `ssone`)
- [x] Output list of strings of the form `e1, e2, e3, ..` where _e1_, e_2, ... are either string literals `"abcd"` or expressions which will evaluate to strings (maybe leave out `[` and `]` because we want to solution to generalise to strings that are already contained within an existing list of strings)
- [x] Develop a tool (webapp) in order to write and edit prompts for this scope. The tool should support also a parametrisation with variables.
- [x] Develop a tool (webapp) in order to write and edit the input sentences for the LLM.
