### ISSUE TITLE
TODO: 23/10-30/10

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/authoring-assistant#3]
- [x] Characterise larger problem space, and scope of current project
  - [x] Larger space: embedding data analysis within a textual explanation of the analysis (literate data science?)
    - [x] Contrast with the existing solutions such as notebooks where we want the text to be in a sense verifiable/certified
  - [x] Smaller space: assuming we have already completed (part of) the analysis, direct referencing of the results of said analysis
  - [x] Potential users/use-cases: policy reports, scientific papers, data journalism, educators  
- [ ] Catalogue linguistic categories to use as examples for transparent text repo
  - [x] Graded adjectives, example: “certain” for probability of 1.0, “virtually certain” for probability of 0.99
  - [x] Mereology (part-whole), example: introducing a scope (say a chart), walking into the chart correctly when discussing parts of the chart
  - [x] Iterators, example: for each chart in the figure, the first bar represents X quantity
  - [ ] Quantitative expressions
- [x] Complete refactoring in explorable-viz/fluid#1076 
  - [x] Merge syntax of records and dictionaries, excise records from the surface language
  - [x] Pretty print all dictionaries in the same way: `{ ["x"] : e }`
  - [x] potentially keep distinction between var/exprkey for dictionaries in the core language
- [ ] IPCC Summary for Policymakers example
  - [ ] Include Fluid source code
  - [ ] Align data set as closely as possible to Table SPM.1
- [x] Potentially retitle paper to include: self-certifying text, data-driven discourse
- [x]  Related work:
   - [x] multiverse analysis
   - [x] explorable explanations
   - [x] Above are not necessarily transparent
- [ ] TODO’s inline with current paper
  - [x] reading from a csv 
  - [ ] “future work” we want to include in the current paper
  - [x] Some sort of multiverse using filtered outputs, could be part of the artifact, would be a product of multiviews 
- [ ] Future work
  - [ ] intentional explanations
  - [ ] intermediate values: a graded adjective might be a representation of a quantitative value, so for transparency we wish to be able to interrogate steps
