### ISSUE TITLE
IPCC AR6: Figure SPM.4b

### ISSUE THREAD

**Issue by JosephBond** [explorable-viz/authoring-assistant#5]
![image](https://github.com/user-attachments/assets/156717a5-5702-41e4-95c6-6f8fe1db29f7)

Want our multiple barchart example to reflect this example
### Code Improvements
- [x] Change title on html page
- [ ] In order to shift to using the exact data from the IPCC report, we need to complete the negative-bars task
### Missing Features
- [ ] Negative bars - explorable-viz/fluid#1184
- [ ] Finer-grained selections on bar-charts 
  - [ ] Need to be able to select components other than `z` of a bar-segment, ie the `y` and `x` values (or their fields) - explorable-viz/fluid#168
- [ ] Whiskers at the tip of bars for confidence intervals -  explorable-viz/fluid#1185
- [x] explorable-viz/fluid#270
- [ ] Present as facet plot: one view containing all charts, then an individual view for each subchart - explorable-viz/fluid#1183

Related: explorable-viz/fluid#1161
